# Generated by Django 4.2.3 on 2024-05-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uodated',
            new_name='updated',
        ),
    ]
